// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus_api.Infrastructure.Data;

#nullable disable

namespace Nexus_api.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260329013531_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nexus")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus_api.Domain.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("duration");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("idClient");

                    b.Property<int>("IdSector")
                        .HasColumnType("int")
                        .HasColumnName("idSector");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdSector");

                    b.ToTable("cases", "nexus");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSector")
                        .HasColumnType("int")
                        .HasColumnName("idSector");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("WebPage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("webPage");

                    b.HasKey("Id");

                    b.HasIndex("IdSector");

                    b.ToTable("clients", "nexus");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.RolTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("RolTeam", "nexus");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("sectors", "nexus");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("IdCase")
                        .HasColumnType("int")
                        .HasColumnName("idCase");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdRolTeam")
                        .HasColumnType("int")
                        .HasColumnName("idRolTeam");

                    b.HasKey("IdCase", "IdUser");

                    b.HasIndex("IdRolTeam");

                    b.HasIndex("IdUser");

                    b.ToTable("Team", "nexus");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", "nexus");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Case", b =>
                {
                    b.HasOne("Nexus_api.Domain.Entities.Client", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus_api.Domain.Entities.Sector", "Sector")
                        .WithMany("Cases")
                        .HasForeignKey("IdSector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Client", b =>
                {
                    b.HasOne("Nexus_api.Domain.Entities.Sector", "Sector")
                        .WithMany("Clients")
                        .HasForeignKey("IdSector")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Nexus_api.Domain.Entities.Case", "Case")
                        .WithMany("TeamMembers")
                        .HasForeignKey("IdCase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus_api.Domain.Entities.RolTeam", "Role")
                        .WithMany("TeamMembers")
                        .HasForeignKey("IdRolTeam")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus_api.Domain.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Case", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Client", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.RolTeam", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Nexus_api.Domain.Entities.User", b =>
                {
                    b.Navigation("TeamMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
